language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run build

deploy:
  provider: surge
  project: ./build/
  domain: elijahquartey.com

on:
  branch: master
